---
  
- name: Installing nginx
  apt:
    name: "nginx"
    state: present

- name: Copying nginx configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
      - { src: 'default', dest: '/etc/nginx/sites-available/default' }

- name: Enable and start nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes

