---
  
- name: Installing dnsmasq
  apt:
    name: "dnsmasq"
    state: present

- name: Copying dns configuration
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
      - { src: 'dnsmasq.conf', dest: '/etc/dnsmasq.conf' }
      - { src: 'hosts', dest: '/etc/hosts' }

- name: Enable and start dnsmasq service
  systemd:
    name: dnsmasq
    state: started
    enabled: yes

