name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        
      - name: Push frontend to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: angelocarly/starbar/starbar-frontend
          tag_with_ref: true
          path: ./frontend
        
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: angelocarly/starbar/starbar-backend
          tag_with_ref: true
          path: ./backend
